import { IEnumDisplayMap } from "../../enumDisplayMap";

export const addLookupValuesToDisplayMap = (map: IEnumDisplayMap) => {
	map.AccessType = {
		1: 'Easy access',
		10: 'Road access',
		11: 'No access',
		12: 'Unknown',
		13: 'Front & Rear Drive Access',
		14: 'Allowed Access',
		15: 'Highway Nearby',
		16: 'Ferry Access',
		17: 'Private Road',
		18: 'Public Road',
		19: 'See Remarks',
		2: 'Highway access',
		20: 'Marina Docking',
		21: 'Private Docking',
		22: 'Public Docking',
		3: 'Rail access',
		4: 'Boat access',
		6: 'Right-of-way',
		7: 'Year-round access',
		8: 'River access',
		9: 'Water access'
    };

	map.Amenities = {
		1: 'Shopping Area',
		10: 'Living Accommodation',
		11: 'Catering/Food Sales',
		12: 'Commercial Condominium',
		13: 'Common Area Indoors',
		14: 'Compound',
		15: 'Entertainment/Video',
		16: 'Exercise Centre',
		17: 'Façade',
		18: 'Florist',
		19: 'Food Services',
		2: 'Storage - Locker',
		20: 'Licensed Dining',
		21: 'Recreation Centre',
		22: 'Residence',
		23: 'Restaurant',
		24: 'Shared Laundry',
		25: 'Street Lighting',
		26: 'Separate Electricity Meters',
		27: 'Separate Heating Controls',
		28: 'Unknown',
		29: 'Gazebo',
		3: 'Laundry Facility',
		30: 'Assisted Living',
		31: 'Guest Suite',
		32: 'Laundry - Coin Op',
		33: 'Laundry - In Suite',
		34: 'Picnic Area',
		35: 'RV Storage',
		36: 'Secured Parking',
		37: 'Skating',
		38: 'Storage - In Suite',
		39: 'Tobogganing',
		4: 'Balconies',
		40: 'Swimming',
		41: 'Ceiling - 9ft',
		42: 'Ceiling - 10ft',
		43: 'Detectors - CO2',
		44: 'Security Window/Bars',
		45: 'Sunroom/Solarium',
		46: 'Vaulted Ceiling',
		47: 'Vinyl Windows',
		48: 'Music Room',
		49: 'Party Room',
		5: 'Mezzanine',
		50: 'Sauna',
		51: 'Whirlpool',
		52: 'Air Conditioning',
		53: 'Furnished',
		54: 'Unfurnished',
		55: 'Clubhouse',
		56: 'Dining Facility',
		57: 'Other',
		58: 'Cable TV',
		59: 'Fireplace(s)',
		6: 'Storefront',
		60: 'Indoor Parking',
		61: 'Multi-Use Rooms',
		62: 'Racquet Courts',
		63: 'Security Room',
		64: 'Security/Concierge',
		65: 'See Remarks',
		7: 'Daycare',
		8: 'Car Wash',
		9: 'Canopy'
    };

	map.AmenitiesNearby = {
		1: 'Golf Course',
		10: 'Marina',
		11: 'CEGEP',
		12: 'Church',
		13: 'Hospital',
		14: 'Public Transit',
		16: 'University',
		17: 'Stores',
		18: 'School yard',
		19: 'Ski area',
		2: 'Recreation',
		20: 'Unknown',
		21: 'Water Nearby',
		22: 'Golf Nearby',
		23: 'Railway',
		24: 'Recreation Nearby',
		25: 'Walking Trails',
		26: 'Place of Worship',
		27: 'Outdoor Skating Rink',
		28: 'Indoor Skating Rink',
		29: 'Beach',
		3: 'Shopping',
		4: 'Airport',
		5: 'Playground',
		6: 'Ski hill',
		7: 'Schools',
		8: 'Highway',
		9: 'Park'
    };

	map.Amperage = {
		1: '60 Amp Service',
		2: '100 Amp Service',
		3: '200 Amp Service',
		4: '600 Amp Service'
    };

	map.Appliances = {
		1: 'All',
		10: 'Water softener',
		11: 'Hot Tub',
		12: 'Satellite Dish',
		13: 'Sauna',
		14: 'Central Vacuum',
		15: 'Jacuzzi',
		16: 'Whirlpool',
		17: 'Barbeque',
		18: 'Intercom',
		19: 'Cooktop - Electric',
		2: 'Washer',
		20: 'Cooktop - Gas',
		21: 'Cooktop - Propane',
		25: 'Oven - Propane',
		26: 'Unknown',
		27: 'None',
		28: 'Gas stove(s)',
		29: 'Range - Gas',
		3: 'Dryer - Electric',
		30: 'Range - Electric',
		31: 'Dishwasher',
		32: 'Wall Mounted TV',
		33: 'Home Theatre',
		34: 'Smart Box',
		35: 'Wine Fridge',
		36: 'Stove',
		37: 'Range',
		38: 'Oven',
		39: 'Dryer',
		4: 'Dryer - Gas',
		40: 'Microwave',
		41: '2 Refrigerators & 2 Stoves',
		42: 'Alarm System',
		43: 'Cooktop',
		44: 'Compactor',
		45: 'Freezer',
		46: 'Garburator',
		47: 'Microwave Range Hood Combo',
		48: 'Oven - Built-In',
		49: 'Alarm System - Roughed In',
		5: 'Refrigerator',
		50: 'Central Vacuum - Roughed In',
		51: 'Wet Bar',
		52: 'Window Air Conditioner',
		53: 'Electronic Air Cleaner',
		54: 'Humidifier',
		55: 'Water Treatment',
		56: 'Hood Fan',
		57: 'Washer/Dryer Combo',
		58: 'Fridge/Stove Combo',
		59: 'Blinds',
		6: 'Oven - Electric',
		60: 'Drapes/Curtains',
		62: 'Food Centre',
		63: 'Furniture',
		64: 'Fixed Machinery & Equipment Incl',
		65: 'Household Goods Included',
		66: 'Hot Water Instant',
		67: 'Mobile Machinery & Equipment Inc',
		68: 'See remarks',
		69: 'Play structure',
		7: 'Oven - gas',
		70: 'Storage Shed',
		71: 'Space Heater',
		72: 'Two stoves',
		74: 'Water Distiller',
		75: 'Window Coverings',
		76: 'Two Washers',
		78: 'Garage door opener',
		79: 'Garage door opener remote(s)',
		8: 'Water meter',
		80: 'Satellite dish receiver',
		81: 'Satellite dish related hardware',
		82: 'Fan',
		83: 'Bar dry',
		84: 'Freezer - Stand Up',
		85: 'Freezer - Chest',
		86: 'Jetted Tub',
		87: 'Microwave Built-in',
		88: 'Washer & Dryer',
		89: 'C/Vac Attachments',
		9: 'Water purifier',
		90: 'Washer/Dryer Stack-Up',
		91: 'Window/Sleeve Air Conditioner',
		92: 'Water Heater - Electric',
		93: 'Water Heater - Gas',
		94: 'Water Heater - Oil',
		95: 'Water Heater - Propane',
		96: 'Water Heater - Tankless',
		97: 'Water Heater'
    };

	map.ArchitecturalStyle = {
		1: 'Bungalow',
		100: 'Neighbourhood',
		103: 'Unknown',
		105: 'Cabin',
		107: 'Tower',
		108: 'High rise',
		109: 'Low rise',
		110: 'Multi-Unit',
		111: 'Cab-Over',
		112: 'Mobile Home',
		113: 'Loft',
		114: 'Cross Dock',
		115: 'Lower Level',
		116: 'Off 2nd Floor',
		117: 'Raised Ranch w/ Bonus Room',
		12: 'Ranch',
		14: 'Tudor',
		15: 'Westcoast',
		16: 'Other',
		19: 'Raised ranch',
		2: 'Character',
		28: 'Raised bungalow',
		29: 'Split entry bungalow',
		3: 'Cottage',
		31: 'Multi-level',
		4: 'Custom',
		41: 'Contemporary',
		42: 'Cathedral entry',
		44: 'Basement entry',
		45: 'Ground level entry',
		49: 'Bi-level',
		52: 'Penthouse',
		53: 'Hillside Bungalow',
		56: 'Cape Cod',
		61: 'A-Frame',
		67: 'Split level entry',
		68: 'Chalet',
		69: 'Camp',
		73: 'Mini',
		75: '2 Level',
		76: '3 Level',
		77: '4 Level',
		78: '5 Level',
		79: 'None',
		9: 'Log house/cabin',
		95: 'Luxury Villa',
		96: 'Carriage',
		97: 'Church'
    };

	map.BasementDevelopment = {
		1: 'Finished',
		16: 'Unknown',
		17: 'Not Applicable',
		18: 'Basement Suite - Regulation',
		19: 'Basement Suite - Non Regulation',
		2: 'Partially finished',
		20: 'Other, See Remarks',
		3: 'Unfinished'
    };

	map.BasementFeatures = {
		10: 'Six feet and over',
		11: 'Less than six feet.',
		12: 'Apartment in basement',
		13: 'Unrestricted height',
		14: 'Separate entrance',
		15: 'Walk out',
		18: 'Unknown',
		19: 'Low',
		20: 'Slab',
		21: 'Walk-up',
		22: 'Suite'
    };

	map.BasementType = {
		17: 'Unknown',
		18: 'Common',
		19: 'Remodeled Basement',
		20: 'Dugout',
		21: 'See Remarks',
		22: 'N/A',
		4: 'Full',
		5: 'Partial',
		6: 'Under floor space',
		7: 'Crawl space',
		8: 'Cellar',
		9: 'None'
    };

	map.Boards = {
		1: 'Vancouver Island Real Estate Board',
		10: 'REALTORS® Association of Edmonton',
		100: 'Quinte & District Association of REALTORS® Inc.',
		109: 'Chambre immobilière de l\'Outaouais',
		11: 'Kamloops & District Real Estate Association',
		114: 'Niagara Association of REALTORS®',
		115: 'Chambre immobilière de Saguenay-Lac St-Jean',
		12: 'Kootenay Association of REALTORS®',
		121: 'The Real Estate Board of Fredericton Area Inc.',
		122: 'Fort McMurray REALTORS®',
		123: 'Chambre immobilière de l\'Estrie',
		13: 'London and St. Thomas Association of REALTORS®',
		14: 'REALTORS® Association of Hamilton-Burlington',
		15: 'Oakville, Milton & District Real Estate Board',
		16: 'Kitchener-Waterloo Association of REALTORS®',
		17: 'Barrie & District Association of REALTORS® Inc.',
		19: 'Okanagan-Mainline Real Estate Board',
		2: 'BC Northern Real Estate Board',
		20: 'Cambridge Association of REALTORS® Inc.',
		23: 'Brandon Area REALTORS®',
		24: 'Southern Georgian Bay Association of REALTORS®',
		25: 'Central Alberta REALTORS® Association',
		26: 'Lethbridge & District Association of REALTORS®',
		27: 'Saskatchewan REALTORS® Association',
		3: 'Victoria Real Estate Board',
		30: 'Simcoe & District Real Estate Board',
		31: 'Peterborough & Kawarthas Association REALTORS®',
		32: 'Chatham Kent Association of REALTORS®',
		33: 'Woodstock-Ingersoll Real Estate Board',
		34: 'Windsor-Essex County Association of REALTORS®',
		35: 'Sudbury Real Estate Board',
		36: 'Yellowknife Real Estate Board',
		37: 'Kingston & Area Real Estate Association',
		38: 'Grande Prairie & Area Association of REALTORS®',
		4: 'Chilliwack & District Real Estate Board',
		41: 'Brantford Regional Real Estate Assn Inc',
		43: 'REALTORS® Association of Grey Bruce Owen Sound',
		44: 'Guelph & District Association of REALTORS®',
		45: 'Greater Moncton REALTORS® du Grand Moncton',
		46: 'Kawartha Lakes Real Estate Association',
		47: 'Muskoka Haliburton Orillia – The Lakelands Association of REALTORS®',
		49: 'Medicine Hat Real Estate Board Co-op',
		5: 'Quebec Professional Association of Real Estate Brokers',
		50: 'Northumberland Hills Association of REALTORS®',
		51: 'Huron Perth Association of REALTORS®',
		53: 'Tillsonburg District Real Estate Board',
		54: 'Chambre Immobilière de La Mauricie',
		6: 'Fraser Valley Real Estate Board',
		61: 'North Bay Real Estate Board',
		64: 'Sault Ste. Marie Real Estate Board',
		65: 'Alberta West REALTORS® Association',
		66: 'REALTORS® Association of South Central Alberta',
		7: 'Winnipeg Regional Real Estate Board',
		70: 'REALTORS® Association of Lloydminster & District',
		76: 'Ottawa Real Estate Board',
		77: 'Renfrew County Real Estate Board',
		8: 'South Okanagan Real Estate Board',
		82: 'Toronto Regional Real Estate Board',
		83: 'Powell River Sunshine Coast Real Estate Board',
		84: 'Saint John Real Estate Board Inc',
		85: 'Mississauga Real Estate Board',
		86: 'Brampton Real Estate Board',
		88: 'Durham Region Association of REALTORS®',
		89: 'Real Estate Board Of Greater Vancouver',
		9: 'Calgary Real Estate Board',
		90: 'Timmins, Cochrane & Timiskaming District Association of REALTORS®',
		91: 'Thunder Bay Real Estate Board',
		92: 'Chambre immobilière de l\'Abitibi-Témiscamingue',
		93: 'Rideau - St. Lawrence Real Estate Board',
		94: 'Chambre immobilière du Centre du Québec',
		95: 'Sarnia-Lambton Real Estate Board',
		97: 'Cornwall & District Real Estate Board'
    };

	map.BuildingType = {
		1: 'House',
		10: 'Manufacturing',
		12: 'Special Purpose',
		13: 'Parking',
		14: 'Other',
		15: 'No Building',
		16: 'Row / Townhouse',
		17: 'Apartment',
		18: 'Recreational',
		19: 'Fourplex',
		2: 'Duplex',
		20: 'Garden Home',
		21: 'Flex Facility',
		22: 'Unknown',
		23: 'Multi-Tenant Industrial',
		24: 'Commercial Mix',
		25: 'Two Apartment House',
		26: 'Modular',
		27: 'Manufactured Home/Mobile',
		28: 'Commercial Apartment',
		29: 'Manufactured Home',
		3: 'Triplex',
		30: 'Park Model Mobile Home',
		4: 'Multi-Family',
		5: 'Residential Commercial Mix',
		6: 'Mobile Home',
		7: 'Offices',
		8: 'Retail',
		9: 'Warehouse'
    };

	map.BusinessSubType = {
		1: 'Apartments',
		10: 'Boarding house',
		100: 'Appliance sales',
		101: 'Appliance service',
		102: 'Auction',
		103: 'Audio sales',
		104: 'Audio service',
		105: 'Auto wreckers',
		106: 'Banquet hall',
		107: 'Billiard',
		108: 'Bookkeeping',
		109: 'Carpentry',
		11: 'Boat sales',
		110: 'Coffee shop',
		111: 'Confectionary',
		112: 'Construction',
		113: 'Contract maintenance',
		114: 'Dating service',
		115: 'Department store',
		116: 'Donut/Coffee shop',
		117: 'Electrical sales',
		118: 'Electrical service',
		119: 'Farm Equipment',
		12: 'Book store',
		120: 'Feedlot',
		121: 'Fish & Chips',
		122: 'Frozen foods',
		123: 'Furniture repair',
		124: 'Go Carts',
		125: 'Golf course',
		126: 'Haulage',
		127: 'Health foods',
		128: 'Hotel/Tavern',
		129: 'Kennel',
		13: 'Bowling alley',
		130: 'Lawn & garden',
		131: 'Market garden',
		132: 'Meat packing',
		133: 'Nut shop',
		134: 'Office machines',
		135: 'Paint & Wallpaper',
		136: 'Plumbing',
		137: 'Recreation',
		138: 'Rent-All',
		139: 'Repair shop',
		14: 'Building lot/supplies',
		140: 'Restaurant/Banquet',
		141: 'Restaurant/Bowling',
		142: 'Retirement home',
		143: 'Stationery',
		144: 'Sub shop',
		145: 'Taxi',
		146: 'Television sales',
		147: 'Television service/repairs',
		148: 'Travel agency',
		149: 'Variety store',
		15: 'Butcher shop',
		150: 'Workshop equipment',
		151: 'Wood shop',
		152: 'Beef farm',
		153: 'Greenhouse',
		154: 'Orchard',
		155: 'Vineyard',
		156: 'General sales/services',
		157: 'Offices',
		158: 'Residential',
		159: 'Residential/Commercial',
		16: 'Campground',
		160: 'Aviary',
		161: 'Bee farm',
		162: 'Berry farm',
		163: 'Fish farm',
		164: 'Fur farm',
		165: 'Hog farm',
		166: 'Mushroom farm',
		167: 'Nursery',
		168: 'Sheep farm',
		169: 'Vegetable farm',
		17: 'Candy shop',
		170: 'Worm farm',
		171: 'Automotive',
		172: 'Dry Cleaning/laundry',
		173: 'Nursing/Hospital',
		174: 'Appliance',
		175: 'Audio',
		176: 'Electrical',
		177: 'Gifts',
		178: 'Television',
		179: 'Farm/ranch',
		18: 'Car wash',
		180: 'Lumber',
		181: 'Miscellanous services',
		182: 'Misc retail',
		183: 'Automotive/aircraft',
		184: 'Drugs/cosmetics',
		185: 'Dry goods/fashion',
		186: 'Hardware/decorating',
		187: 'Hotel/motel',
		188: 'Manufacturing/wholesale',
		189: 'Restaurant/fast food',
		19: 'Cards/gifts',
		190: 'Exotic animal farm',
		191: 'Gravel yard',
		192: 'Mixed farm',
		193: 'Hobby farm',
		194: 'Goat farm',
		195: 'Tree farm',
		196: 'Potato farm',
		197: 'Sod farm',
		198: 'Tobacco farm',
		199: 'Institution',
		2: 'Auto body',
		20: 'Carpeting/Rugs',
		200: 'Marina/Resort',
		201: 'Retail & offices',
		202: 'Retail/residential',
		203: 'Office/residential',
		204: 'High Tech',
		205: 'Restaurant/pub',
		206: 'Retail/offices/residential',
		207: 'Heavy industrial',
		208: 'Light industrial',
		209: 'Sales/service',
		21: 'Caterer',
		210: 'Vegetable/fruit farm',
		211: 'Mixed use farm',
		212: 'Grocery',
		213: 'Retail misc.',
		214: 'Miscellaneous services',
		215: 'Industrial',
		216: 'Mixed - IC&I',
		217: 'Business',
		218: 'Residential/Commercial/Offices',
		219: 'Beauty shop',
		22: 'Computer store',
		220: 'Cottage/Cabin Rental',
		221: 'Tourist',
		222: 'Antiques',
		223: 'Arts & Crafts',
		224: 'Sporting Goods',
		225: 'Inn (6 bedrooms plus)',
		226: 'Tanning Salon',
		227: 'Cinema/Theatre',
		228: 'Hairdressing Salon',
		229: 'Accounting',
		23: 'Consultants',
		230: 'Health Centre',
		231: 'Breeding',
		232: 'Wrapping',
		233: 'Maple Sugar Bush',
		234: 'Fruits & Vegetables',
		235: 'Lingerie',
		236: 'Factory',
		237: 'Massotherapy',
		238: 'Pastry Shop',
		239: 'Outfitter',
		24: 'Convenience store',
		240: 'Distribution Road',
		241: 'Specialized residence',
		242: 'Parking Lot',
		243: 'Tobacco Store',
		244: 'Agriculture',
		245: 'Outside storage',
		246: 'Single tenant rental',
		247: 'Licensed student dwelling',
		248: 'Townhouse / row unit rental',
		249: 'Wholesale',
		25: 'Clothing store',
		250: 'Special purpose',
		251: 'Industrial hi tech',
		252: 'Unknown',
		253: 'Pet Grooming',
		254: 'Recycling',
		256: 'School',
		257: 'Bar/Hotel',
		258: 'Beauty/Hair',
		259: 'Daycare/Children',
		26: 'Crop farm',
		260: 'Grocery/Mini Mart',
		261: 'Other Retail',
		262: 'Other Services',
		263: 'Packing Building',
		264: 'Day Spa',
		265: 'Marina/Resort',
		266: 'Liquor Store',
		267: 'Mobile Food and Beverage',
		268: 'Cannabis',
		27: 'Craft store',
		28: 'Dairy farm',
		29: 'Day Care',
		3: 'Auto parts',
		30: 'Decorators/shops',
		31: 'Deli',
		32: 'Diner',
		33: 'Disco',
		34: 'Diving shop',
		35: 'Dry cleaning',
		36: 'Laundry',
		37: 'Electronics store',
		38: 'Entertainment',
		39: 'Fast foods',
		4: 'Auto sales',
		40: 'Florist/Gifts',
		41: 'Frame shop',
		42: 'Food store',
		43: 'Furniture/household',
		44: 'Gas station',
		45: 'General commercial',
		46: 'General industrial',
		47: 'General retail',
		48: 'Hardware store',
		49: 'Health club',
		5: 'Auto service/repair',
		50: 'Horse farm',
		51: 'Hospital',
		52: 'Hotel',
		53: 'Ice Cream shop',
		54: 'Jewelry',
		55: 'Laundromat',
		56: 'Lawn equipment',
		57: 'Marina',
		58: 'Marine equipment',
		59: 'Manufacturing',
		6: 'Bakery',
		60: 'Motel',
		61: 'Music',
		62: 'Mobile home park',
		63: 'Moving/Trucking',
		64: 'News/Magazines',
		65: 'Night club',
		66: 'Nursing home',
		67: 'Office supplies',
		68: 'Personal consumer service',
		69: 'Pet & supplies',
		7: 'Bar/tavern',
		70: 'Pharmacy',
		71: 'Photography',
		72: 'Pizza shop',
		73: 'Plants/Nurseries',
		74: 'Poultry farm',
		75: 'Print shop',
		76: 'Professional office(s)',
		77: 'Pub',
		78: 'Religious',
		79: 'Resort',
		8: 'Barber/beauty shop',
		80: 'Restaurant',
		81: 'Seafood sales',
		82: 'Security systems',
		83: 'Shoe repair',
		84: 'Shopping center',
		85: 'Specialty shop',
		86: 'Sports & Recreation',
		87: 'Storage/Mini',
		88: 'Strip mall',
		89: 'Tailor shop',
		9: 'Bed & Breakfast',
		90: 'Trucking',
		91: 'Video store',
		92: 'Warehouse',
		93: 'See remarks',
		94: 'Specialty retail',
		95: 'Manufacturing/Warehouse',
		96: 'High Technology',
		97: 'Truck garage',
		98: 'Industrial Commercial',
		99: 'Other'
    };

	map.BusinessType = {
		400: 'Accommodation',
		401: 'Agriculture, Forestry, Fishing and Hunting',
		402: 'Automobile',
		403: 'Construction',
		404: 'Food Services and Beverage',
		405: 'Industrial',
		406: 'Institutional',
		407: 'Manufacturing',
		408: 'Other',
		409: 'Personal Services',
		410: 'Recreation',
		411: 'Restaurant',
		412: 'Resort',
		413: 'Retail and Wholesale',
		414: 'Residential',
		415: 'Special Purpose',
		416: 'Service',
		417: 'Professional, Scientific and Hi Tech Services',
		418: 'Arts and Entertainment',
		419: 'Remediation Services',
		420: 'Consulting',
		421: 'Education Services',
		422: 'Finance and Insurance',
		423: 'Administrative and Support',
		424: 'Transportation and Warehousing',
		425: 'Utilities',
		426: 'Waste Management',
		427: 'Real Estate',
		428: 'Health Care and Social Assistance',
		429: 'Hospitality',
		430: 'Mining and Oil and Gas',
		431: 'Unknown',
		432: 'Information and Cultural Industries'
    };

	map.CeilingType = {
		1: 'Suspended ceiling',
		2: 'Tile ceiling',
		3: 'Sheetrock (Drywall)',
		4: 'Plaster',
		5: 'Vaulted',
		6: 'Cathedral',
		7: 'Domed',
		8: 'Open',
		9: 'Unknown'
    };

	map.ClearCeilingHeight = {
		0: 'Under 10 Feet',
		10: '10 to Under 14 Feet',
		14: '14 to Under 16 Feet',
		16: '16 to Under 18 Feet',
		18: '18 to Under 20 Feet',
		20: '20 to Under 22 Feet',
		22: '22 to Under 24 Feet',
		24: '24 to Under 28 Feet',
		28: 'Over 28 Feet'
    };

	map.CommunicationType = {
		1: 'Internet Access',
		10: 'Switches',
		11: 'satellite Internet access',
		12: 'Cable Internet access',
		13: 'ISDN access',
		14: 'Firewall',
		15: 'LAN',
		16: 'WAN',
		17: 'Unknown',
		18: 'High Speed Internet',
		19: 'Fiber',
		2: 'Patch Panel',
		3: 'DSL',
		4: 'Modem',
		5: 'Climate controlled server room',
		6: 'Server Racks',
		7: 'Servers',
		8: 'PC',
		9: 'Routers'
    };

	map.CommunityFeatures = {
		1: 'Adult Oriented',
		10: 'Lake Privileges',
		11: 'School Bus',
		12: 'Public Swimming Pool',
		13: 'Pets Allowed',
		14: 'Bus Route',
		15: 'Community Centre',
		16: 'Fishing',
		17: 'Industrial Park',
		18: 'Public Washrooms',
		19: 'Recreational Facilities',
		2: 'Family Oriented',
		20: 'High Population Density',
		21: 'Unknown',
		22: 'Pet Restrictions',
		23: 'Pets Allowed With Restrictions',
		24: 'Rentals Allowed',
		25: 'Rentals Not Allowed',
		26: 'Rentals Allowed With Restrictions',
		27: 'Age Restrictions',
		3: 'Golf Course Development',
		4: 'Mobiles Allowed',
		5: 'Pets not Allowed',
		6: 'Quiet Area',
		7: 'Rural Setting',
		8: 'Seniors Oriented',
		9: 'High Traffic Area'
    };

	map.ConstructionMaterial = {
		1: 'Insulbrick',
		10: 'ICF Block',
		11: 'Concrete Walls',
		2: 'Poured concrete',
		3: 'Straw bales',
		4: 'Wood frame',
		5: 'Concrete block',
		6: 'Masonry',
		7: 'Steel frame',
		8: 'Log',
		9: 'Unknown'
    };

	map.ConstructionStatus = {
		1: 'New',
		2: 'Renovated',
		3: 'Under Construction',
		4: 'Under Renovation',
		5: 'Complete',
		6: 'Unknown',
		7: 'Shell',
		8: 'Insulation upgraded'
    };

	map.ConstructionStyleAttachment = {
		1: 'Attached',
		10: 'Strip mall',
		11: 'Shopping centre',
		12: 'Other',
		13: 'Unknown',
		3: 'Detached',
		4: 'Front and back',
		5: 'Semi-detached',
		6: 'Side by side',
		7: 'Stacked',
		8: 'Up and down',
		9: 'Link'
    };

	map.ConstructionStyleOther = {
		1: 'Manufactured',
		10: 'Other',
		11: 'Unknown',
		12: 'Basement',
		13: 'Office Tower',
		2: 'Modular',
		3: 'Seasonal',
		4: 'Super Store',
		5: 'General Purpose',
		6: 'Distribution',
		7: 'Truck Terminal',
		8: 'Service Centre',
		9: 'Showroom'
    };

	map.ConstructionStyleSplitLevel = {
		1: 'Backsplit',
		2: 'Sidesplit',
		3: 'Split level',
		4: 'Other',
		5: 'Unknown'
    };

	map.CoolingType = {
		1: 'Central air conditioning',
		10: 'Heat Pump',
		11: 'Air Conditioned',
		12: 'Ductless',
		13: 'See Remarks',
		2: 'Partially air conditioned',
		3: 'Window air conditioner',
		4: 'Air exchanger',
		5: 'Ventilation system',
		6: 'Fully air conditioned',
		7: 'Wall unit',
		8: 'Unknown',
		9: 'None'
    };

	map.Crop = {
		1: 'Barley',
		10: 'Wheat',
		11: 'Rice',
		12: 'Grains',
		13: 'Tobacco',
		14: 'Sod',
		15: 'Fruits',
		16: 'Mixed Vegetables',
		17: 'Plants/Flowers',
		18: 'Herbs',
		19: 'Carrots',
		2: 'Beans',
		20: 'Cucumbers',
		21: 'Onions',
		22: 'Pea Crops',
		23: 'Potatoes',
		25: 'Sugar Beets',
		26: 'Tomatoes',
		27: 'Grapes',
		28: 'Mushrooms',
		29: 'Berries',
		3: 'Corn',
		30: 'Strawberries',
		31: 'Raspberries',
		32: 'Blueberries',
		33: 'Melons',
		34: 'Pumpkins',
		35: 'Peppers',
		36: 'Apples',
		37: 'Pears',
		38: 'Plums',
		39: 'Cherries',
		4: 'Sweet Corn',
		40: 'Cranberries',
		41: 'Tree',
		42: 'Unknown',
		43: 'Vegetable & Fruit',
		44: 'Alfalfa',
		45: 'Canola',
		46: 'Cannabis',
		5: 'Hay',
		6: 'Hops',
		7: 'Kale/Cole',
		8: 'Oats',
		9: 'Soybeans'
    };

	map.CurrentUse = {
		1: 'Agriculture - active',
		10: 'Equestrian',
		11: 'Gravel Yard',
		12: 'Hobby Farm',
		13: 'Industrial',
		14: 'Mixed use',
		15: 'Mobile home',
		16: 'Other',
		17: 'Orchard',
		18: 'Open pit',
		19: 'Pasture',
		2: 'Agriculture - inactive',
		20: 'Quarry',
		21: 'Ranch',
		22: 'Range',
		23: 'Recreational',
		24: 'Vineyard',
		25: 'No special use',
		26: 'No land',
		27: 'Unknown',
		3: 'Country residential',
		4: 'Development commercial',
		5: 'Development office',
		6: 'Development residential',
		7: 'Development retail',
		8: 'Development industrial',
		9: 'Development other'
    };

	map.DocumentType = {
		1: 'Floor Plan',
		2: 'Site Plan',
		3: 'Original Blueprints',
		4: 'Water Certificate',
		5: 'Financial Statements',
		6: 'Financial Analysis',
		7: 'Unknown'
    };

	map.Easement = {
		1: 'Sub Division Covenants',
		10: 'Escarpment Control',
		11: 'See Site plan',
		12: 'Other',
		13: 'Unknown',
		14: 'By-Law Restriction',
		15: 'Leased',
		16: 'Oil/Gas/Mineral Rights',
		17: 'None',
		2: 'Easement',
		3: 'Right of way',
		4: 'Flood Plain',
		5: 'Environment protected',
		6: 'Overhead Right of Way',
		7: 'Surface Right of Way',
		8: 'Underground Right of Way',
		9: 'Encroachment'
    };

	map.EquipmentType = {
		1: 'Water Heater - Electric',
		10: 'Rental Fridge',
		11: 'Rental Stove - Electric',
		12: 'Rental Stove - Gas',
		13: 'Rental Water Softener',
		14: 'Unknown',
		15: 'Water Heater',
		16: 'None',
		17: 'Dryer(s)',
		18: 'Fridge(s)',
		19: 'Stove(s)',
		2: 'Water Heater - Gas',
		20: 'Washer(s)',
		21: 'Other',
		22: 'Air Conditioner',
		23: 'HRV',
		24: 'Water Softener',
		25: 'Water Heater - Tankless',
		26: 'Heat Pump',
		27: 'Dusk to Dawn Light',
		3: 'Water Heater - Oil',
		4: 'Water Heater - Propane',
		5: 'Furnace',
		6: 'Propane Tank',
		7: 'Rental Washer',
		8: 'Rental Dryer - Electric',
		9: 'Rental Dryer - Gas'
    };

	map.ExteriorFinish = {
		1: 'Steel',
		10: 'Cedar covering joint',
		11: 'Pressed fibre',
		12: 'Sheathing brick paper',
		13: 'Stone',
		14: 'Brick imitation',
		15: 'Rock imitation',
		16: 'Stucco',
		17: 'Vinyl',
		18: 'Aluminum siding',
		19: 'Glass',
		2: 'Aggregate',
		20: 'Hardboard',
		21: 'Precast concrete',
		22: 'Wood siding',
		23: 'Vinyl siding',
		24: 'Aluminum trim',
		25: 'Unknown',
		26: 'Cedar Siding',
		27: 'Log Siding',
		28: 'Metal',
		29: 'See Remarks',
		3: 'Asbestos',
		30: 'Log',
		31: 'Siding',
		32: 'Composite Siding',
		33: 'Colour Loc',
		34: 'Concrete Block',
		35: 'Concrete Siding',
		36: 'Insul Brick',
		37: 'Other',
		38: 'Brick Facing',
		39: 'Aluminum',
		4: 'Asphalt',
		40: 'Aluminum/Vinyl',
		41: 'Concrete/Stucco',
		42: 'Masonite',
		43: 'Shingles',
		44: 'Engineered Wood Siding',
		5: 'Cedar shingles',
		6: 'Concrete',
		7: 'Wood',
		8: 'Wood shingles',
		9: 'Brick'
    };

	map.FarmType = {
		1: 'Animal',
		10: 'Greenhouse',
		11: 'Unknown',
		12: 'Mixed',
		13: 'Farm',
		14: 'Other',
		15: 'See Remarks',
		16: 'Packing Building',
		2: 'Boarding',
		3: 'Cash Crop',
		4: 'Feed Lot',
		5: 'Nursery',
		6: 'Market Gardening',
		7: 'Hobby Farm',
		8: 'Vineyard',
		9: 'Orchard'
    };

	map.Features = {
		1: 'Acreage',
		106: 'Back lane',
		107: 'Handicap access',
		108: 'Paved lane',
		111: 'No back lane',
		112: 'Park/reserve',
		114: 'Subdividable lot',
		115: 'Hardwood bush',
		116: 'Softwood bush',
		118: 'Conservation/green belt',
		119: 'Golf course/parkland',
		121: 'Hazardous land',
		122: 'Wetlands',
		125: 'Lane',
		126: 'Rectangular',
		131: 'Pie',
		132: 'Wedge',
		141: 'Wet bar',
		15: 'Hillside',
		150: 'Storm & screens',
		161: 'Elevator',
		184: 'Bicycle parking',
		197: 'Potential recreational',
		20: 'Level lot',
		200: 'Will consider trade',
		21: 'Low maintenance yard',
		211: 'Beach',
		216: 'Conveyor',
		217: 'Crane',
		219: 'Dock height loading',
		220: 'Door 10 to 15 ft.',
		221: 'Door under 10 ft.',
		222: 'Doors 15 to 20 ft.',
		225: 'Freight elevator',
		228: 'Hoists',
		232: 'Central island',
		233: 'Levelers',
		234: 'Lighting',
		237: 'None',
		250: 'Waterfront loading',
		251: 'Wheelchair access',
		252: 'Window display',
		254: 'Balcony',
		256: 'Double width or more driveway',
		257: 'Paved driveway',
		258: 'Crushed stone driveway',
		259: 'Plain paving stone driveway',
		261: 'Wood cupboard',
		262: 'Melamine cupboard',
		263: 'Laminated cupboard',
		27: 'Park setting',
		272: 'Garbage disposal unit',
		273: 'Trash compactor',
		274: 'Embedded oven',
		275: 'Central cooking island',
		276: 'Cooking surface',
		287: 'Aluminium window',
		288: 'Wood windows',
		289: 'PVC window',
		3: 'Beach property',
		30: 'Private setting',
		310: 'No neighbours behind',
		311: 'Lot with lake',
		318: 'Bathroom Adjoining Primary Bedroom',
		319: 'Podium bath',
		320: 'Separate shower',
		321: 'Jacuzzi bath-tub',
		348: 'Dry well',
		351: 'Sliding windows',
		352: 'Hung windows (Guillotine)',
		353: 'Crank windows',
		354: 'French window',
		355: 'French door',
		360: 'Broadloom Upgraded',
		361: 'Closet Organizers',
		362: 'Dance Floor',
		364: 'Exterior Walls- 2x6"',
		367: 'No Animal Home',
		368: 'No Smoking Home',
		370: 'Drapery Rods',
		371: 'Silent Floor Joists',
		372: 'Skylight',
		376: 'Swirlpool bath (Jacuzzi)',
		377: 'Built-in wall unit',
		380: 'Air lines',
		384: 'Bathroom with separate shower',
		399: 'Crops',
		40: 'Southern exposure',
		401: 'Crown leases available',
		402: 'Divisible',
		403: 'Dock levelers',
		405: 'Dry',
		408: 'Environmental reserve',
		42: 'Treed',
		429: 'Gently Rolling',
		43: 'Underground services',
		431: 'Gravel lane',
		432: 'Handicapped provisions',
		434: 'Heavy bush',
		437: 'Industrial condominium',
		438: 'Industrial mall/subdivision',
		439: 'Inside load',
		442: 'Leasehold improvements',
		443: 'Level',
		445: 'Loading dock seals',
		448: 'Marine Oriented',
		449: 'Marketing quotas',
		450: 'Marsh',
		452: 'Medium bush',
		453: 'Medium Rolling',
		457: 'Moorage',
		458: 'Mountain',
		459: 'Natural light',
		460: 'No bush',
		462: 'No services',
		465: 'Office space',
		466: 'Oil/grease interceptors',
		467: 'On rail trackage',
		469: 'Overhead doors',
		472: 'Partially serviced',
		473: 'Passenger elevator',
		474: 'Paved yard',
		478: 'Pole sign',
		482: 'Pylon  sign',
		484: 'Rail',
		485: 'Rear loading',
		496: 'Signs allowed',
		497: 'Signs provided',
		499: 'Slatted floors',
		5: 'Central location',
		50: 'Wooded area',
		514: 'Tenant improvement',
		52: 'Corner Site',
		524: 'Yard drainage',
		525: 'Flat',
		526: 'Tile Drained',
		529: 'Hilly',
		536: 'Year Round Living',
		537: 'Carpet Free',
		538: 'Private Elevator',
		539: 'Glass Elevator',
		54: 'Irregular lot size',
		55: 'Rocky',
		562: 'Granite Countertops',
		563: 'Wood Countertops',
		564: 'Laminate Countertops',
		565: 'Corion Countertops',
		566: 'Slate Countertops',
		567: 'Metallic Countertops',
		57: 'Sloping',
		571: 'Shoreline Owned',
		572: 'Mixed Bush',
		593: 'No Driveway',
		61: 'See remarks',
		625: 'Non Paved Driveway',
		627: 'Shared Driveway',
		631: 'Heavy loading',
		632: 'Gated community',
		633: 'Country residential',
		634: 'Within city limits',
		635: 'Recreational',
		636: 'In suite Laundry',
		637: 'Gazebo',
		638: 'Assisted Living',
		639: 'Guest Suite',
		640: 'Laundry- Coin operated',
		641: 'Picnic Area',
		642: 'air climatisé mural',
		644: 'Central Exhaust',
		645: 'Landing Strip',
		646: 'No Pet Home',
		647: 'Sump Pump',
		648: 'Structural wood basement floor',
		649: 'Balcony enclosed',
		65: 'Rail trackage',
		650: 'Energy Efficient',
		651: 'Automatic Garage Door Opener',
		652: 'Solar Equipment',
		653: 'Balcony/Deck/Patio',
		654: '2nd Kitchen',
		655: 'Atrium/Sunroom',
		656: 'Circular Driveway',
		657: 'Concrete Driveway',
		658: 'Covered Porch',
		659: 'Finished Driveway',
		66: 'Visual exposure',
		660: 'Front Driveway',
		661: 'Grade Entrance',
		662: 'Gravel Driveway',
		663: 'In-Law Suite',
		664: 'Interlocking Driveway',
		665: 'Mutual Driveway',
		666: 'One Balcony',
		668: 'Private Yard',
		669: 'Random Tiled',
		67: 'Ravine',
		670: 'Rear Driveway',
		671: 'Sandy Beach',
		672: 'Sauna',
		673: 'Side Driveway',
		674: 'Single Driveway',
		675: 'Three Balconies',
		676: 'Treed Lot',
		677: 'Two Balconies',
		678: 'Walk-In Closet',
		679: 'Greenspace',
		680: 'Gas BBQ Hookup',
		681: 'Single Family',
		682: 'Agriculture',
		683: 'Vacant Land',
		684: 'Office',
		685: 'Retail',
		686: 'Business',
		687: 'Industrial',
		688: 'Parking',
		689: 'Institutional - Special Purpose',
		690: 'Multi-family',
		691: 'Hospitality',
		692: 'VisitAble',
		7: 'Cul-de-sac',
		71: 'Hobby farm',
		74: 'Rolling',
		76: 'Partially cleared',
		79: 'Backs on greenbelt',
		8: 'Curb & gutter',
		80: 'Tiled',
		81: 'Waterway',
		82: 'Open space',
		84: 'Bush',
		85: 'Resort',
		87: 'Farm setting',
		88: 'Handicapped adaptable',
		90: 'Flat site',
		94: 'Other'
    };

	map.FenceType = {
		1: 'Fence',
		10: 'Board',
		11: 'Chain link',
		12: 'Wrought iron',
		13: 'Privacy',
		14: 'Electric',
		15: 'No Fence',
		16: 'Unknown',
		17: 'Other',
		18: 'Fully Fenced',
		2: 'Not fenced',
		3: 'Partially fenced',
		4: 'Fenced yard',
		5: 'Cross fenced',
		6: 'Barbed Wire',
		7: 'Page Wire',
		8: 'Rail',
		9: 'Cedar rail'
    };

	map.FireplaceFuel = {
		1: 'Wood',
		2: 'Gas',
		3: 'Electric',
		4: 'Mixed',
		5: 'Pellet',
		6: 'Propane',
		7: 'Unknown',
		8: 'Oil'
    };

	map.FireplaceType = {
		1: 'Free Standing Metal',
		10: 'Brick Facing',
		11: 'Corner',
		12: 'Double-sided',
		13: 'Heatilator/Fan',
		14: 'Marble fac',
		15: 'Other - See remarks',
		16: 'Roughed in',
		17: 'Stone',
		18: 'Stove',
		19: 'Tile Facing',
		2: 'Insert',
		20: 'Direct vent',
		21: 'Glass Door',
		3: 'Woodstove',
		4: 'Rough In',
		5: 'Conventional',
		6: 'Heatillator',
		7: 'Decorative',
		8: 'None',
		9: 'Unknown'
    };

	map.FireProtection = {
		1: 'Alarm system',
		10: 'Unknown',
		11: 'Monitored Alarm',
		12: 'Security Window Bars',
		13: 'Full Sprinkler System',
		14: 'No Sprinkler System',
		15: 'None',
		16: 'Partial Sprinkler System',
		17: 'Smoke Detector Only',
		2: 'Security system',
		3: 'Security guard',
		4: 'Security',
		5: 'Split security(man/electric)',
		6: 'Smoke Detectors',
		7: 'Sprinkler System-Fire',
		8: 'Controlled entry',
		9: 'Fire alarm system'
    };

	map.Fixture = {
		1: 'All',
		2: 'None',
		3: 'Ceiling fans',
		4: 'Drapes/Window coverings',
		5: 'Venetian blinds',
		6: 'TV Antenna',
		7: 'Chandelier',
		8: 'Unknown',
		9: 'List of Fixtures Available'
    };

	map.FlooringType = {
		1: 'Concrete',
		10: 'Stone',
		11: 'Carpet tiles',
		12: 'Heavy loading',
		13: 'Other',
		14: 'Unknown',
		15: 'Ceramic',
		16: 'Floating',
		17: 'Ceramic Tile',
		18: 'Linoleum',
		19: 'Vinyl',
		2: 'Tile',
		20: 'Vinyl Tile',
		21: 'Wood',
		22: 'Cork',
		23: 'Porcelain Tile',
		24: 'Wall-to-wall carpet',
		25: 'Carpet over Hardwood',
		26: 'Mixed Flooring',
		27: 'Concrete Slab',
		28: 'Bamboo',
		29: 'Ceramic/Porcelain',
		3: 'Hardwood',
		30: 'Cushion/Lino/Vinyl',
		32: 'Marble/Granite/Quartz',
		33: 'Softwood',
		4: 'Laminate',
		5: 'Slate',
		6: 'Marble',
		7: 'Parquet',
		8: 'Carpeted',
		9: 'Engineered hardwood'
    };

	map.FoundationType = {
		1: 'Wood',
		10: 'None',
		11: 'Brick',
		12: 'Brick/Stone',
		13: 'Pillars & Posts',
		14: 'See Remarks',
		15: 'Slab',
		16: 'Wood/Piers',
		17: 'Concrete Block',
		2: 'Stone',
		3: 'Block',
		4: 'Concrete Perimeter',
		5: 'Concrete Slab',
		6: 'Piled',
		7: 'Unknown',
		8: 'Concrete',
		9: 'Poured Concrete'
    };

	map.FrontsOn = {
		1: 'Road',
		10: 'Garden',
		11: 'Unknown',
		12: 'Paved Road',
		2: 'Highway',
		3: 'Waterfront',
		4: 'Alley',
		5: 'Paved Yard',
		6: 'Courtyard',
		7: 'Frontyard',
		8: 'Backyard',
		9: 'Parking lot'
    };

	map.HeatingFuel = {
		20: 'Oil',
		21: 'Heating oil',
		22: 'Stove oil',
		23: 'Waste oil',
		24: 'Electric',
		25: 'Natural gas',
		26: 'Propane',
		27: 'Combination',
		28: 'Solar',
		29: 'Wood',
		30: 'Pellet',
		31: 'Coal',
		32: 'Bi energy',
		33: 'Other',
		34: 'Unknown',
		35: 'Geo Thermal',
		36: 'See Remarks',
		37: 'Wind Power'
    };

	map.HeatingType = {
		1: 'Heat Pump',
		10: 'Slow-burning stove',
		11: 'Forced air',
		12: 'Radiant/Infra-red Heat',
		13: 'Underfloor ducts',
		14: 'Wall Heaters',
		15: 'Gravity Heat System',
		16: 'Overhead Heaters',
		17: 'Ground Source Heat',
		18: 'Not known',
		19: 'No heat',
		2: 'Air circulation heat',
		20: 'In Floor Heating',
		21: 'Outside Furnace',
		22: 'Boiler',
		23: 'Space Heater',
		24: 'Heat Recovery Ventilation (HRV)',
		25: 'High-Efficiency Furnace',
		26: 'See remarks',
		27: 'Central heating',
		28: 'Floor heat',
		29: 'Coil Fan',
		3: 'Hot water radiator heat',
		30: 'Other',
		31: 'Radiator',
		32: 'Electric Air Cleaner',
		33: 'Hot Water',
		34: 'Wood Stove',
		35: 'Wall Mounted Heat Pump',
		36: 'Central Heat Pump',
		37: 'Ductless',
		38: 'Furnace',
		4: 'Baseboard heaters',
		5: 'Electric baseboard units',
		6: 'Space heating baseboards',
		7: 'Radiant heat',
		8: 'Steam radiator',
		9: 'Stove'
    };

	map.IrrigationType = {
		1: 'Flood',
		2: 'Guide pivot',
		3: 'Hand Move',
		4: 'Pivot',
		5: 'Power sources',
		6: 'Wheel move',
		7: 'Unknown'
    };

	map.LandDispositionType = {
		1: 'Fenced',
		2: 'Cleared',
		3: 'Pasture',
		4: 'Tillable',
		5: 'Tile Drained',
		6: 'Unknown'
    };

	map.LandscapeFeatures = {
		1: 'Landscaped',
		10: 'Fully landscaped',
		11: 'Irrigation sprinkler(s)',
		12: 'Lawn sprinkler',
		13: 'Underground sprinkler',
		14: 'Sprinkler system',
		15: 'Sprinkler',
		16: 'Unknown',
		17: 'Xeriscaping',
		2: 'Fruit trees/shrubs',
		3: 'Vegetable garden',
		4: 'Partially landscaped',
		5: 'Not landscaped',
		6: 'Lawn',
		7: 'Garden Area',
		8: 'Land / Yard lined with hedges',
		9: 'Fruit trees'
    };

	map.LeaseType = {
		1: 'Gross',
		10: 'Semi-Gross',
		2: 'Gross Escalating',
		3: 'Net',
		4: 'Net Escalating',
		5: 'Triple Net',
		6: 'Percentage',
		7: 'Unknown',
		8: 'Net or Percentage',
		9: 'Other, See Remarks'
    };

	map.LiveStockType = {
		1: 'Beef',
		10: 'Alpaca',
		11: 'Deer',
		12: 'Elk',
		13: 'Buffalo',
		14: 'Chicken',
		15: 'Turkey',
		16: 'Duck',
		17: 'Goose',
		18: 'Pheasant',
		19: 'Quail',
		2: 'Calf',
		20: 'Pidgeon',
		21: 'Bee',
		22: 'Dog',
		23: 'Cat',
		24: 'Salmon',
		25: 'Game Fish',
		26: 'Shellfish',
		27: 'Mussells',
		28: 'Clams',
		29: 'Scallops',
		3: 'Cow',
		30: 'Snails',
		31: 'Chinchilla',
		32: 'Mink',
		33: 'Fox',
		34: 'Fish',
		35: 'Poultry',
		36: 'Dairy',
		37: 'Exotic Animals',
		38: 'Stock included',
		39: 'Unknown',
		4: 'Goat',
		40: 'Stock Not Included',
		5: 'Hog',
		6: 'Horse',
		7: 'Rabbit',
		8: 'Sheep',
		9: 'Worm'
    };

	map.LoadingType = {
		1: 'Truck level',
		2: 'Grade level',
		3: 'Rail siding',
		4: 'Freight Access',
		5: 'Other',
		6: 'Unknown'
    };

	map.Machinery = {
		1: 'Tractor',
		10: 'Large Square Bailer',
		11: 'Round Bailer',
		12: 'Bale Thrower',
		13: 'Grain Auger',
		14: 'Hay Elevator',
		15: 'Fertilizer Spreader',
		16: 'Manure Spreader',
		17: 'Overhead Crane',
		18: 'Forklift',
		19: 'Container Lift Crane',
		2: 'Combine',
		20: 'Unknown',
		21: 'All',
		3: 'Skid Steer',
		4: 'Gravity Box',
		5: 'Hay Wagon',
		6: 'Livestock Trailer',
		7: 'Livestock Truck',
		8: 'Sprayer',
		9: 'Small Square Bailer'
    };

	map.MaintenanceFeeType = {
		1: 'Common Area Maintenance',
		10: 'Security',
		11: 'Waste Removal',
		12: 'Unknown',
		13: 'Cable TV',
		14: 'Caretaker',
		15: 'Ground Maintenance',
		16: 'Heat',
		17: 'Electricity',
		18: 'Water',
		19: 'Insurance',
		2: 'Electrical Repairs',
		20: 'Other, See Remarks',
		21: 'Condominium Amenities',
		22: 'Parking',
		23: 'Recreation Facilities',
		24: 'Reserve Fund Contributions',
		25: 'Residential Manager',
		26: 'Sewer',
		27: 'Parcel of Tied Land',
		3: 'Exterior Maintenance',
		4: 'Interior Maintenance',
		5: 'Lawn Care',
		6: 'Landscaping',
		7: 'Plumbing Repairs',
		8: 'Property Inspection',
		9: 'Property Management'
    };

	map.MeasureUnit = {
		1: 'square feet',
		10: 'hectares',
		2: 'feet',
		4: 'square meters',
		5: 'meters',
		7: 'acres'
    };

	map.OwnershipType = {
		1: 'Condominium/Strata',
		10: 'Life Lease',
		11: 'Freehold Condo',
		12: 'Strata',
		13: 'Condominium',
		14: 'Cooperative',
		15: 'Other, See Remarks',
		16: 'Leasehold/Leased Land',
		17: 'Bare Land Condo',
		2: 'Leasehold Condo/Strata',
		3: 'Freehold',
		4: 'Leasehold',
		5: 'Timeshare/Fractional',
		6: 'Shares in Co-operative',
		7: 'Partial',
		8: 'Unknown',
		9: 'Undivided Co-ownership'
    };

	map.ParkingType = {
		1: 'Attached Garage',
		10: 'Parking Pad',
		11: 'Paved Yard',
		12: 'Other',
		13: 'None',
		14: 'Unknown',
		15: 'No Garage',
		16: 'Parking Space(s)',
		17: 'Parkade',
		18: 'Stall',
		19: 'Breezeway',
		2: 'Integrated Garage',
		20: 'Offset',
		21: 'Rear',
		22: 'RV',
		23: 'Street',
		24: 'Oversize',
		25: 'See Remarks',
		26: 'Inside Entry',
		27: 'Gravel',
		28: 'Interlocked',
		29: 'Shared',
		3: 'Detached Garage',
		30: 'Street Permit',
		31: 'Surfaced',
		32: 'Tandem',
		33: 'Exposed Aggregate',
		34: 'Visitor Parking',
		35: 'Boat House',
		36: 'Concrete',
		37: 'Heated Garage',
		38: 'Electric Vehicle Charging Station(s)',
		4: 'Garage',
		5: 'Carport',
		6: 'Underground',
		7: 'Indoor',
		8: 'Open',
		9: 'Covered'
    };

	map.PaymentUnit = {
		1: 'Daily',
		10: 'Seasonal',
		2: 'Weekly',
		3: 'Bi-weekly',
		4: 'Monthly',
		5: 'Bi-monthly',
		6: 'Quarterly',
		7: 'Yearly',
		8: 'Fixed',
		9: 'Unknown'
    };

	map.PoolFeatures = {
		10: 'Slide',
		11: 'Diving Board',
		13: 'Unknown',
		14: 'Salt Water Pool',
		6: 'Pool equipment',
		7: 'Heated pool',
		8: 'Kidney Shaped',
		9: 'Lap Pool'
    };

	map.PoolType = {
		1: 'Pool',
		12: 'Unknown',
		13: 'On Ground Pool',
		2: 'Inground pool',
		3: 'Above ground pool',
		4: 'Indoor pool',
		5: 'Outdoor pool'
    };

	map.PropertyType = {
		300: 'Single Family',
		301: 'Recreational',
		302: 'Agriculture',
		303: 'Vacant Land',
		304: 'Office',
		305: 'Retail',
		306: 'Business',
		307: 'Industrial',
		308: 'Parking',
		309: 'Institutional - Special Purpose',
		310: 'Multi-family',
		311: 'Other',
		312: 'Hospitality'
    };

	map.RentalEquipmentType = {
		1: 'Water Heater - Electric',
		10: 'Rental Fridge',
		11: 'Rental Stove - Electric',
		12: 'Rental Stove - Gas',
		13: 'Rental Water Softener',
		14: 'Unknown',
		15: 'Water Heater',
		16: 'None',
		17: 'Dryer(s)',
		18: 'Fridge(s)',
		19: 'Stove(s)',
		2: 'Water Heater - Gas',
		20: 'Washer(s)',
		21: 'Other',
		22: 'Air Conditioner',
		23: 'HRV',
		24: 'Water Softener',
		25: 'Water Heater - Tankless',
		26: 'Heat Pump',
		27: 'Dusk to Dawn Light',
		3: 'Water Heater - Oil',
		4: 'Water Heater - Propane',
		5: 'Furnace',
		6: 'Propane Tank',
		7: 'Rental Washer',
		8: 'Rental Dryer - Electric',
		9: 'Rental Dryer - Gas'
    };

	map.RightType = {
		10: 'Unknown',
		2: 'Water Rights',
		3: 'Mineral Rights',
		4: 'Timber Rights',
		5: 'Grazing Rights',
		6: 'Beach Rights',
		7: 'Foreshore Rights',
		8: 'Air Rights',
		9: 'Riparian Rights'
    };

	map.RoadType = {
		1: 'Gravel road',
		2: 'No thru road',
		3: 'Paved road',
		4: 'Road Not Maintained',
		5: 'Seasonal Road',
		6: 'Dirt Road',
		7: 'Unknown',
		8: 'Cul de sac'
    };

	map.RoofMaterial = {
		1: 'Asphalt shingle',
		10: 'Unknown',
		11: 'Metal',
		14: 'Clay Tile',
		15: 'Concrete Tile',
		16: 'Fiberglass',
		17: 'Pine Shakes',
		18: 'Roll Roofing',
		2: 'Steel',
		20: 'Vinyl Shingles',
		22: 'Asphalt and Gravel',
		23: 'Concrete',
		24: 'Other',
		25: 'See Remarks',
		27: 'Shakes',
		3: 'Tar & gravel',
		4: 'Tile',
		5: 'Cedar shake',
		6: 'Wood Shingle',
		7: 'Membrane',
		8: 'Tin',
		9: 'Asphalt'
    };

	map.RoofStyle = {
		101: 'Mansard',
		102: 'Flat',
		103: 'Conventional',
		104: 'Peaked',
		105: 'Cottage',
		106: 'Unknown'
    };

	map.RoomLevel = {
		1: 'Second level',
		10: 'Other',
		11: 'Sub-basement',
		12: 'Upper Level',
		13: 'Unknown',
		14: 'Ground level',
		15: 'In between',
		16: 'Loft',
		17: 'Sixth Level',
		2: 'Third level',
		3: 'Fourth level',
		4: 'Fifth level',
		5: 'Above',
		6: 'Basement',
		7: 'Flat',
		8: 'Lower level',
		9: 'Main level'
    };

	map.RoomType = {
		1: 'Living room',
		10: 'Bedroom 4',
		100: 'Music',
		101: 'Media',
		102: 'Wine Cellar',
		103: 'Bedroom - Bachelor',
		104: 'Hall',
		105: 'Lobby',
		106: 'Roughed-In Bathroom',
		107: 'Computer Room',
		108: 'Bonus Room',
		109: 'Photography-dark room',
		11: 'Bedroom 5',
		110: 'Second Kitchen',
		111: 'Laundry / Bath',
		112: 'Flex Space',
		12: 'Bedroom 6',
		13: 'Laundry room',
		14: 'Partial bathroom',
		15: 'Additional bedroom',
		16: 'Conservatory',
		17: 'Eating area',
		18: 'Full bathroom',
		19: 'Full ensuite bathroom',
		2: 'Dining room',
		20: 'Foyer',
		21: 'Storage',
		22: 'Hobby room',
		23: 'Partial ensuite bathroom',
		24: 'Recreational, Games room',
		25: 'Enclosed porch',
		26: 'Workshop',
		27: 'Utility room',
		28: 'Solarium',
		29: 'Living room/Dining room',
		3: 'Kitchen',
		30: 'Addition',
		31: 'Atrium',
		32: 'Bath (# pieces 1-6)',
		33: 'Bedroom',
		34: 'Cold room',
		35: 'Dinette',
		36: 'Dining nook',
		37: 'Ensuite (# pieces 2-6)',
		38: 'Great room',
		39: 'Jacuzzi',
		4: 'Family room',
		40: 'Kitchen/Dining room',
		41: 'Loft',
		42: 'Mud room',
		43: 'Other',
		44: 'Sauna',
		45: 'Library',
		46: '1pc Bathroom',
		47: '2pc Bathroom',
		48: '3pc Bathroom',
		49: '4pc Bathroom',
		5: 'Den',
		50: '5pc Bathroom',
		51: '6pc Bathroom',
		52: '1pc Ensuite bath',
		53: '2pc Ensuite bath',
		54: '3pc Ensuite bath',
		55: '4pc Ensuite bath',
		56: '5pc Ensuite bath',
		57: '6pc Ensuite bath',
		58: 'Steam room',
		59: 'Party room',
		6: 'Family bathroom',
		60: 'Office',
		61: 'In-law suite',
		62: 'Rental unit',
		63: 'Guest suite',
		64: 'Sunroom',
		65: 'Attic (finished)',
		66: 'Playroom',
		67: 'Games room',
		68: 'Balcony',
		69: 'Fruit cellar',
		7: 'Primary Bedroom',
		70: 'Florida/Fireplace',
		71: 'Florida room',
		72: 'Family room/Fireplace',
		73: 'Living room/Fireplace',
		74: 'Porch',
		75: 'Sunroom/Fireplace',
		77: 'Sitting room',
		78: 'Eat in kitchen',
		79: 'Recreation room',
		8: 'Bedroom 2',
		80: 'Gym',
		81: 'Exercise room',
		82: 'Ensuite',
		83: 'Inlaw suite',
		84: 'Multi-use room',
		85: 'Lunchroom',
		86: 'Mezzanine',
		87: 'Not known',
		88: 'Flat',
		89: 'Breakfast',
		9: 'Bedroom 3',
		90: 'Nursery',
		91: 'Furnace',
		92: 'Pantry',
		93: 'Study',
		94: 'Beverage room',
		95: 'Bathroom',
		96: 'Attic',
		97: 'Walk Up Attic',
		99: 'Muskoka Room'
    };

	map.Sewer = {
		1: 'No sewage system',
		10: 'Unknown',
		11: 'Holding Tank',
		12: 'Septic Tank and Field',
		13: 'Ejector System',
		14: 'Gravity',
		16: 'Mound',
		17: 'See remarks',
		18: 'Pump',
		19: 'Facultative Lagoon',
		2: 'Municipal sewage system',
		20: 'Septic Field',
		3: 'Sanitary sewer',
		4: 'Storm sewer',
		5: 'Septic tank without purification field',
		6: 'Septic tank',
		7: 'Sealed septic tank',
		8: 'Septic System',
		9: 'Private sewer'
    };

	map.StoreFront = {
		1: 'Interior Storefront',
		2: 'Exterior Storefront',
		3: 'Unknown'
    };

	map.SignType = {
		1: 'Signband',
		2: 'Pylon',
		3: 'Directory Board',
		4: 'Store front',
		5: 'Facia',
		6: 'None',
		7: 'Unknown'
    };

	map.SoilEvaluationType = {
		1: 'Completed',
		2: 'Pending',
		3: 'Not Completed',
		4: 'Unknown',
		5: 'See agent',
		6: 'None'
    };

	map.SoilType = {
		1: 'Clay',
		10: 'Unknown',
		11: 'Heavy',
		12: 'Light',
		13: 'Otonabee Loam',
		14: 'Rocky',
		15: 'Sandy Beach',
		16: 'See Remarks',
		17: 'Wet',
		18: 'Sand',
		19: 'Gravel',
		2: 'Mixed soil',
		3: 'No stones',
		4: 'Sand/gravel',
		5: 'Some stones',
		6: 'Stones',
		7: 'Stony',
		8: 'Loam',
		9: 'Peat'
    };

	map.StorageType = {
		1: 'Locker',
		10: 'Dry Holding Tank',
		11: 'Unknown',
		12: 'Manure Pit',
		13: 'Unit',
		2: 'Storage Shed',
		3: 'Holding Tank',
		4: 'Outside Storage',
		5: 'Storage',
		6: 'Storage in Basement',
		7: 'Silo',
		8: 'Feed Storage',
		9: 'Liquid Holding Tank'
    };

	map.StructureType = {
		1: 'Sidewalk',
		10: 'Tennis Court',
		11: 'Playground',
		12: 'Breakwall',
		13: 'Wharf',
		14: 'Playstructure',
		15: 'Outbuilding',
		16: 'Workshop',
		17: 'Shed',
		18: 'Boathouse',
		19: 'Greenhouse',
		2: 'Dock',
		20: 'Atrium',
		21: 'Clubhouse',
		22: 'Playhouse',
		23: 'Porch',
		24: 'Bank Barn',
		25: 'Equestrian Arena',
		26: 'Equestrian Track',
		27: 'Frame Barn',
		28: 'Paddocks/Corralls',
		29: 'Milk Parlour',
		3: 'Patio(s)',
		30: 'Pole Barn',
		31: 'Drive Shed',
		32: 'Silo',
		33: 'Coverall',
		34: 'Dog Run - Fenced In',
		35: 'Fire Pit',
		36: 'Unknown',
		37: 'Labour Housing',
		38: 'Barn',
		39: 'Building',
		4: 'Sundeck',
		40: 'Plane Hangar',
		41: 'Crop',
		42: 'Livestock',
		43: 'Machinery',
		44: 'None',
		45: 'Arena',
		46: 'Concrete Silo',
		47: 'See Remarks',
		48: 'Steel Silo',
		49: 'Track',
		5: 'Breakwater',
		50: 'Track House',
		6: 'Deck',
		7: 'Concrete terrace',
		8: 'Wood terrace',
		9: 'Squash & Raquet Court'
    };

	map.SurfaceWater = {
		1: 'Creek through',
		10: 'Permanent Slough',
		11: 'Some Sloughs',
		12: 'No Sloughs',
		13: 'Unknown',
		14: 'Dugout',
		15: 'Lake/Pond',
		16: 'River/Stream',
		2: 'Creeks',
		3: 'Ponds',
		4: 'Spring(s)',
		5: 'Well(s)',
		6: 'Pond or Stream',
		7: 'Creek or Stream',
		8: 'Lake',
		9: 'Private Lake'
    };

	map.TopographyType = {
		1: 'Hillside',
		10: 'Flat site',
		11: 'Flood plain',
		12: 'Wetlands',
		13: 'Marsh',
		14: 'Hazardous land',
		15: 'Beach',
		16: 'Dry',
		17: 'Gently Rolling',
		18: 'Level',
		19: 'Medium Rolling',
		2: 'Level lot',
		20: 'Mountain',
		21: 'No sloughs',
		22: 'Permanent sloughs',
		23: 'Some sloughs',
		24: 'Flat',
		25: 'Hilly',
		26: 'Unknown',
		3: 'Cleared',
		4: 'Rocky',
		5: 'Sloping',
		6: 'Ravine',
		7: 'Rolling',
		8: 'Waterway',
		9: 'Open space'
    };

	map.TransactionType = {
		1: 'For sale or rent',
		2: 'For sale',
		3: 'For rent',
		4: 'For lease'
    };

	map.UffiCodes = {
		1: 'Yes present',
		2: 'No never present',
		3: 'Removed',
		4: 'Partially removed',
		5: 'Unknown'
    };

	map.UtilityPower = {
		1: '220v Entry',
		10: 'Mixed Phase',
		11: '60 Amp Service',
		12: '120/208 V',
		13: '347/600 V',
		14: 'Generator',
		15: 'None',
		16: '240/400V',
		2: '100 Amp Service',
		3: '200 Amp Service',
		4: '600 Amp Service',
		5: 'Pole Line',
		6: 'Underground to House',
		7: 'Unknown',
		8: 'Single Phase',
		9: 'Three Phase'
    };

	map.UtilityType = {
		1: 'Water',
		10: 'Unknown',
		2: 'Sewer',
		3: 'Natural Gas',
		4: 'Electricity',
		5: 'Cable',
		6: 'Telephone',
		7: 'DSL*',
		8: 'Wireless',
		9: 'Fully serviced'
    };

	map.UtilityWater = {
		1: 'Municipal water',
		10: 'Co-operative Well',
		11: 'Sand point',
		12: 'Unknown',
		13: 'Private Utility',
		14: 'Irrigation District',
		15: 'Well',
		16: 'Community Water System',
		17: 'Creek/Stream',
		18: 'Spring',
		19: 'Community Water User\'s Utility',
		2: 'Ground-level well',
		20: 'Licensed',
		21: 'Government Managed',
		22: 'Dugout',
		23: 'Hand Pump',
		24: 'None',
		25: 'See Remarks',
		26: 'Artesian Well',
		3: 'City water',
		4: 'Cistern',
		5: 'Drilled Well',
		6: 'Shared Well',
		7: 'Lake/River Water Intake',
		8: 'Dug Well',
		9: 'Bored Well'
    };

	map.ViewType = {
		1: 'City view',
		10: 'Property with view',
		12: 'View (panoramic)',
		13: 'Unknown',
		14: 'Waterfront - East',
		15: 'Waterfront - North',
		16: 'Waterfront - North East',
		17: 'Waterfront - North West',
		18: 'Waterfront - South',
		19: 'Waterfront - South East',
		2: 'Lake view',
		20: 'Waterfront - South West',
		21: 'Waterfront - West',
		22: 'Harbour',
		3: 'Mountain view',
		4: 'Ocean view',
		5: 'River view',
		6: 'View',
		7: 'Valley view',
		8: 'View of water',
		9: 'Ravine view'
    };

	map.WaterFrontType = {
		1: 'Waterfront',
		10: 'Deeded water access',
		12: 'Restricted waterfront',
		13: 'Unknown',
		14: 'Waterfront, Road Between',
		15: 'Island',
		16: 'Other',
		2: 'Waterfront on lake',
		3: 'Waterfront on ocean',
		4: 'Waterfront on river',
		5: 'Waterfront on pond',
		6: 'Waterfront on stream',
		7: 'Waterfront on creek',
		8: 'Waterfront nearby',
		9: 'Waterfront on canal'
    };

	map.ZoningType = {
		1: 'Other',
		10: 'Single family dwelling',
		100: 'Professional',
		101: 'Retail',
		102: 'Retail Strata',
		103: 'Townhouse',
		104: 'Townhouse Strata',
		105: 'Variance in Place',
		106: 'Condominium Strata',
		107: 'Conforming Use',
		108: 'Neighborhood Business District',
		109: 'Vacationing area',
		11: 'Residential',
		110: 'Unknown',
		12: 'Residential/Commercial',
		13: 'Non-conforming',
		14: 'Warehouse',
		15: 'Subdivision',
		16: 'Development Site',
		17: 'Recreational',
		18: 'Institutional',
		19: 'Low intensity business',
		2: 'Agricultural',
		20: 'General business',
		21: 'Highway corridor',
		22: 'Commercial mixed use',
		23: 'Neighbourhood convenience commercial',
		24: 'Commercial office',
		25: 'Shopping centre',
		26: 'Direct development control',
		27: 'Comprehensively planned development',
		28: 'Temporary holding',
		29: 'Site specific development control',
		3: 'Commercial',
		30: 'Industrial business',
		31: 'Heavy industrial',
		32: 'Medium Industrial',
		33: 'Low rise apartment',
		34: 'Medium rise apartment',
		35: 'High rise apartment',
		36: 'Single detached residential',
		37: 'Low density infill',
		38: 'Low density redevelopment',
		39: 'Semi-detached redevelopment',
		4: 'Duplex',
		40: 'Row housing',
		41: 'Medium density multiple family',
		42: 'Mobile home',
		43: 'Residential mixed use',
		44: 'Planned lot residential',
		45: 'Rural residential',
		46: 'Commercial/Business/Manufacturing',
		47: 'Light industrial',
		48: 'Highway commercial',
		49: 'Business',
		5: 'In ALR',
		50: 'Parkland',
		51: 'Urban reserve',
		52: 'Public use',
		53: 'Convenience commercial',
		54: 'Rural commercial',
		55: 'Day care facility',
		56: 'Residential low density',
		57: 'Residential medium density',
		58: 'Residential high density',
		59: 'Residential mixed',
		6: 'Industrial',
		60: 'Residential small lot',
		61: 'Restricted small lot',
		62: 'Residential apartment',
		63: 'Heritage mixed use',
		64: 'Mature adult community',
		65: 'Mushroom plant',
		66: 'Reserved for future',
		67: 'Residential 2 dwellings',
		68: 'Residential special community',
		69: 'Residential up/down duplex',
		7: 'Multi-Family',
		70: 'Restricted residential lot',
		71: 'Rural recreational',
		72: 'Small single dwelling',
		73: 'Large single dwelling',
		74: 'Two unit dwelling',
		75: 'Four unit dwelling',
		76: 'Multiple unit dwelling',
		77: 'Restricted residential',
		78: 'Country residential',
		79: 'Downtown commercial',
		80: 'Transitional',
		81: 'Service commercial',
		82: 'Arterial commercial',
		83: 'Park',
		84: 'Contract zone',
		85: 'Light industrial high density',
		86: 'Industrial medium density',
		87: 'Airport industrial',
		88: 'Restricted agricultural',
		89: 'Conservation area',
		9: 'See Remarks',
		90: 'Commercial Strata',
		91: 'Central Business District',
		92: 'Cluster',
		93: 'High Rise',
		94: 'Industrial Strata',
		95: 'Mixed',
		96: 'Multi-Use',
		97: 'Office',
		98: 'Office Strata',
		99: 'Personal Strata'
    };

	map.Boards = {
		1: 'Vancouver Island Real Estate Board',
		10: 'REALTORS® Association of Edmonton',
		100: 'Quinte & District Association of REALTORS® Inc.',
		109: 'Chambre immobilière de l\'Outaouais',
		11: 'Kamloops & District Real Estate Association',
		114: 'Niagara Association of REALTORS®',
		115: 'Chambre immobilière de Saguenay-Lac St-Jean',
		12: 'Kootenay Association of REALTORS®',
		121: 'The Real Estate Board of Fredericton Area Inc.',
		122: 'Fort McMurray REALTORS®',
		123: 'Chambre immobilière de l\'Estrie',
		13: 'London and St. Thomas Association of REALTORS®',
		14: 'REALTORS® Association of Hamilton-Burlington',
		15: 'Oakville, Milton & District Real Estate Board',
		16: 'Kitchener-Waterloo Association of REALTORS®',
		17: 'Barrie & District Association of REALTORS® Inc.',
		19: 'Okanagan-Mainline Real Estate Board',
		2: 'BC Northern Real Estate Board',
		20: 'Cambridge Association of REALTORS® Inc.',
		23: 'Brandon Area REALTORS®',
		24: 'Southern Georgian Bay Association of REALTORS®',
		25: 'Central Alberta REALTORS® Association',
		26: 'Lethbridge & District Association of REALTORS®',
		27: 'Saskatchewan REALTORS® Association',
		3: 'Victoria Real Estate Board',
		30: 'Simcoe & District Real Estate Board',
		31: 'Peterborough & Kawarthas Association REALTORS®',
		32: 'Chatham Kent Association of REALTORS®',
		33: 'Woodstock-Ingersoll Real Estate Board',
		34: 'Windsor-Essex County Association of REALTORS®',
		35: 'Sudbury Real Estate Board',
		36: 'Yellowknife Real Estate Board',
		37: 'Kingston & Area Real Estate Association',
		38: 'Grande Prairie & Area Association of REALTORS®',
		4: 'Chilliwack & District Real Estate Board',
		41: 'Brantford Regional Real Estate Assn Inc',
		43: 'REALTORS® Association of Grey Bruce Owen Sound',
		44: 'Guelph & District Association of REALTORS®',
		45: 'Greater Moncton REALTORS® du Grand Moncton',
		46: 'Kawartha Lakes Real Estate Association',
		47: 'Muskoka Haliburton Orillia – The Lakelands Association of REALTORS®',
		49: 'Medicine Hat Real Estate Board Co-op',
		5: 'Quebec Professional Association of Real Estate Brokers',
		50: 'Northumberland Hills Association of REALTORS®',
		51: 'Huron Perth Association of REALTORS®',
		53: 'Tillsonburg District Real Estate Board',
		54: 'Chambre Immobilière de La Mauricie',
		6: 'Fraser Valley Real Estate Board',
		61: 'North Bay Real Estate Board',
		64: 'Sault Ste. Marie Real Estate Board',
		65: 'Alberta West REALTORS® Association',
		66: 'REALTORS® Association of South Central Alberta',
		7: 'Winnipeg Regional Real Estate Board',
		70: 'REALTORS® Association of Lloydminster & District',
		76: 'Ottawa Real Estate Board',
		77: 'Renfrew County Real Estate Board',
		8: 'South Okanagan Real Estate Board',
		82: 'Toronto Regional Real Estate Board',
		83: 'Powell River Sunshine Coast Real Estate Board',
		84: 'Saint John Real Estate Board Inc',
		85: 'Mississauga Real Estate Board',
		86: 'Brampton Real Estate Board',
		88: 'Durham Region Association of REALTORS®',
		89: 'Real Estate Board Of Greater Vancouver',
		9: 'Calgary Real Estate Board',
		90: 'Timmins, Cochrane & Timiskaming District Association of REALTORS®',
		91: 'Thunder Bay Real Estate Board',
		92: 'Chambre immobilière de l\'Abitibi-Témiscamingue',
		93: 'Rideau - St. Lawrence Real Estate Board',
		94: 'Chambre immobilière du Centre du Québec',
		95: 'Sarnia-Lambton Real Estate Board',
		97: 'Cornwall & District Real Estate Board'
    };

	map.IndividualDesignations = {
		1: 'Accredited Buyer Representative',
		10: 'Certified Manager of Condominiums',
		11: 'Certified Property Manager®',
		12: 'Certified Real Estate Specialist',
		13: 'Certified Real Estate Brokerage Manager',
		14: 'Counselor of Real Estate',
		15: 'Certified in Real Estate Finance',
		16: 'Certified Reserve Planner',
		17: 'Certified Residential Specialist®',
		18: 'Certified Residential  Underwriter',
		19: 'REALTOR e-PRO®',
		2: 'Accredited Buyer Representative Manager',
		20: 'Fellow of the Real Estate Institute',
		21: 'Fellow of the Real Estate Institute (Appraisal Specialist)',
		22: 'Fellow of the Real Estate Institute (Executive)',
		23: 'General Accredited Appraiser',
		24: 'Graduate REALTOR® Institute',
		26: 'Performance Management Network',
		27: 'Residential Accredited Appraiser',
		28: 'REALTOR® Association Certified Executive',
		29: 'Real Estate Professional Assistant',
		3: 'At Home With Diversity Certification',
		30: 'Accredited Appraiser Canadian Institute',
		31: 'Market Value Appraiser-Residential',
		33: 'Accredited Leasing Officer',
		34: 'Accredited Mortgage Professional',
		35: 'Accredited Senior Appraiser',
		36: 'Certified Valuation Analyst',
		37: 'Certified Mold Remediation',
		38: 'Certified Professional Residential Property Manager',
		39: 'Canadian Residential Appraiser',
		4: 'Accredited Land Consultant',
		40: 'Fellows of the Royal Institution of Chartered Surveyors',
		41: 'Member, Appraisal Institute',
		42: 'Professional Land Economist',
		43: 'Real Property Administrator®',
		44: 'Society of Industrial and Office REALTORS®',
		45: 'Senior Residential Appraiser',
		46: 'Canadian Employee Relocation Professional',
		47: 'Canadian Employee Relocation Council Relocation Specialist™',
		48: 'Relocation Resort Specialist',
		49: 'Senior Real Estate Specialist',
		5: 'Accredited Residential Manager®',
		50: 'Certified Lease Professional Designation',
		51: 'Designated Agency Representatives',
		52: 'Distinguished Real Estate Instructor™',
		53: 'Unknown',
		54: 'Certified Condo Specialist',
		55: 'Canadian REALTOR® Association Executive',
		56: 'NAR\'s Green Designation',
		57: 'ACCREDITED GREENAGENT® -Residential',
		58: 'ACCREDITED GREENBROKER® - Commercial',
		59: 'EcoBroker®',
		6: 'Associate Reserve Planner',
		60: 'Transnational Referral Certified',
		61: 'Certified Negotiation Expert',
		62: 'Member of the Royal Institute of Charter Surveyors',
		63: 'Certified Reserve Fund Planner',
		64: 'Accredited Staging Professional',
		65: 'Resort & Second-Home Property Specialist',
		66: 'Short Sales and Foreclose Resource',
		67: 'Business Corporation Owned by a Real Estate Broker',
		68: 'Canadian Personal Property Appraiser',
		69: 'Seller Representative Specialist',
		7: 'Certified Commercial Investment Member',
		70: 'Accredited Senior Agent',
		71: 'Certified Luxury Home Marketing Specialist',
		72: 'Royal Institute of Chartered Surveyors',
		73: 'Accredited Commercial Professional',
		74: 'Master Certified Negotiation Expert',
		75: 'Associate of the Canadian Condominium Institute',
		76: 'Real Estate Negotiation Expert',
		77: 'Military Relocation Professional',
		78: 'Pricing Strategy Advisor',
		79: 'Accredited Luxury Home Specialist',
		8: 'Certified International Property Specialist',
		80: 'Performance Management Network Designation',
		81: 'Certified in Marketing of Real Estate',
		82: 'Residential Construction Certified',
		83: 'Certified New Home Specialist',
		84: 'Chartered Accountant',
		85: 'Chartered Professional Accountant',
		86: 'Certified General Accountant',
		87: 'Certified Management Accountant',
		9: 'Certified Leasing Officer'
    };

	map.Languages = {
		1: 'English',
		10: 'Ukrainian',
		100: 'Uzbek',
		101: 'Xiang',
		102: 'Yiddish',
		103: 'Yue',
		104: 'Tajik',
		105: 'Chaldean',
		106: 'Assyrian',
		107: 'Filipino',
		11: 'Arabic',
		12: 'Dutch',
		13: 'Tagalog (Filipino)',
		14: 'Greek',
		15: 'Vietnamese',
		16: 'Cree',
		17: 'Inuktitut (Inuit)',
		18: 'Japanese',
		19: 'Russian',
		2: 'French',
		20: 'Korean',
		21: 'Slovak',
		22: 'American Sign Language (ASL)',
		23: 'Hindi',
		24: 'Persian',
		25: 'Croatian',
		26: 'Czech',
		27: 'Danish',
		28: 'Hebrew',
		29: 'Hungarian',
		3: 'Chinese (Mandarin)',
		30: 'Latvian',
		31: 'Maltese',
		32: 'Norwegian',
		33: 'Serbian',
		34: 'Turkish',
		35: 'Bulgarian',
		36: 'Chinese (Cantonese)',
		37: 'Swedish',
		38: 'Urdu',
		39: 'Bangla',
		4: 'Italian',
		40: 'Burmese',
		41: 'Romanian',
		42: 'Armenian',
		43: 'Dari',
		44: 'Pashto',
		45: 'Farsi',
		46: 'Tamil',
		47: 'Gujarati',
		48: 'Macedonian',
		49: 'Malaysian',
		5: 'German',
		50: 'Afrikaans',
		51: 'Finnish',
		52: 'Slovenian',
		53: 'Lithuanian',
		54: 'Albanian',
		55: 'Aboriginal languages',
		56: 'Amharic',
		57: 'Azeri',
		58: 'Bahasa Malaysia',
		59: 'Belorussian',
		6: 'Polish',
		60: 'Catalan',
		61: 'Creole',
		62: 'Estonian',
		63: 'Flemish',
		64: 'Friesian',
		65: 'Galla',
		66: 'Gan',
		67: 'Georgian',
		68: 'Hakka',
		69: 'Hausa',
		7: 'Spanish',
		70: 'Icelandic',
		71: 'Indonesian',
		72: 'Javanese',
		73: 'Jin-yu',
		74: 'Kannada',
		75: 'Kazakh',
		76: 'Kejia',
		77: 'Khmer',
		78: 'Kiswahili',
		79: 'Konkani',
		8: 'Portuguese',
		80: 'Kurdish',
		81: 'Lao',
		82: 'Luxembourgish',
		83: 'Malagasy',
		84: 'Malay',
		85: 'Malayalam',
		86: 'Marathi',
		87: 'Miny',
		88: 'Mongolian',
		89: 'Pakhto',
		9: 'Punjabi',
		90: 'Serbo-Croatian',
		91: 'Sindhi',
		92: 'Sinhala',
		94: 'Somali',
		95: 'Sunda',
		96: 'Tchi',
		97: 'Telugu',
		98: 'Thai',
		99: 'Tigrinya'
    };

	map.Specialties = {
		1: 'Property Management',
		10: 'Residential Valuation',
		11: 'Investment',
		12: 'Residential Financing',
		14: 'Residential Leasing',
		16: 'Residential Legal',
		18: 'Residential Relocation',
		2: 'Residential Property Management',
		20: 'Retail',
		21: 'Industrial',
		22: 'Office',
		23: 'Multi-Family',
		24: 'Farm/Ranch',
		25: 'Hospitality',
		26: 'Recreational',
		27: 'Waterfront Properties',
		28: '2nd Home',
		29: 'Luxury Homes',
		3: 'Business Brokerage',
		30: 'Seasonal/Vacation Rentals',
		31: 'Resort Properties',
		32: 'Golf Community Properties',
		33: 'Age Restricted/Active Adult Community Properties',
		35: 'Condos',
		36: 'Agriculture Land',
		4: 'Residential Brokerage',
		5: 'Consulting',
		7: 'Development Land',
		8: 'Residential Development',
		9: 'Appraisal'
    };

	map.Boards = {
		1: 'Vancouver Island Real Estate Board',
		10: 'REALTORS® Association of Edmonton',
		100: 'Quinte & District Association of REALTORS® Inc.',
		109: 'Chambre immobilière de l\'Outaouais',
		11: 'Kamloops & District Real Estate Association',
		114: 'Niagara Association of REALTORS®',
		115: 'Chambre immobilière de Saguenay-Lac St-Jean',
		12: 'Kootenay Association of REALTORS®',
		121: 'The Real Estate Board of Fredericton Area Inc.',
		122: 'Fort McMurray REALTORS®',
		123: 'Chambre immobilière de l\'Estrie',
		13: 'London and St. Thomas Association of REALTORS®',
		14: 'REALTORS® Association of Hamilton-Burlington',
		15: 'Oakville, Milton & District Real Estate Board',
		16: 'Kitchener-Waterloo Association of REALTORS®',
		17: 'Barrie & District Association of REALTORS® Inc.',
		19: 'Okanagan-Mainline Real Estate Board',
		2: 'BC Northern Real Estate Board',
		20: 'Cambridge Association of REALTORS® Inc.',
		23: 'Brandon Area REALTORS®',
		24: 'Southern Georgian Bay Association of REALTORS®',
		25: 'Central Alberta REALTORS® Association',
		26: 'Lethbridge & District Association of REALTORS®',
		27: 'Saskatchewan REALTORS® Association',
		3: 'Victoria Real Estate Board',
		30: 'Simcoe & District Real Estate Board',
		31: 'Peterborough & Kawarthas Association REALTORS®',
		32: 'Chatham Kent Association of REALTORS®',
		33: 'Woodstock-Ingersoll Real Estate Board',
		34: 'Windsor-Essex County Association of REALTORS®',
		35: 'Sudbury Real Estate Board',
		36: 'Yellowknife Real Estate Board',
		37: 'Kingston & Area Real Estate Association',
		38: 'Grande Prairie & Area Association of REALTORS®',
		4: 'Chilliwack & District Real Estate Board',
		41: 'Brantford Regional Real Estate Assn Inc',
		43: 'REALTORS® Association of Grey Bruce Owen Sound',
		44: 'Guelph & District Association of REALTORS®',
		45: 'Greater Moncton REALTORS® du Grand Moncton',
		46: 'Kawartha Lakes Real Estate Association',
		47: 'Muskoka Haliburton Orillia – The Lakelands Association of REALTORS®',
		49: 'Medicine Hat Real Estate Board Co-op',
		5: 'Quebec Professional Association of Real Estate Brokers',
		50: 'Northumberland Hills Association of REALTORS®',
		51: 'Huron Perth Association of REALTORS®',
		53: 'Tillsonburg District Real Estate Board',
		54: 'Chambre Immobilière de La Mauricie',
		6: 'Fraser Valley Real Estate Board',
		61: 'North Bay Real Estate Board',
		64: 'Sault Ste. Marie Real Estate Board',
		65: 'Alberta West REALTORS® Association',
		66: 'REALTORS® Association of South Central Alberta',
		7: 'Winnipeg Regional Real Estate Board',
		70: 'REALTORS® Association of Lloydminster & District',
		76: 'Ottawa Real Estate Board',
		77: 'Renfrew County Real Estate Board',
		8: 'South Okanagan Real Estate Board',
		82: 'Toronto Regional Real Estate Board',
		83: 'Powell River Sunshine Coast Real Estate Board',
		84: 'Saint John Real Estate Board Inc',
		85: 'Mississauga Real Estate Board',
		86: 'Brampton Real Estate Board',
		88: 'Durham Region Association of REALTORS®',
		89: 'Real Estate Board Of Greater Vancouver',
		9: 'Calgary Real Estate Board',
		90: 'Timmins, Cochrane & Timiskaming District Association of REALTORS®',
		91: 'Thunder Bay Real Estate Board',
		92: 'Chambre immobilière de l\'Abitibi-Témiscamingue',
		93: 'Rideau - St. Lawrence Real Estate Board',
		94: 'Chambre immobilière du Centre du Québec',
		95: 'Sarnia-Lambton Real Estate Board',
		97: 'Cornwall & District Real Estate Board'
    };

	map.Franchisor = {
		144139: 'Sutton Head Office',
		161536: 'RE/MAX Ontario Atlantic Canada Inc',
		251019: 'Century 21 Canada Limited Partnership',
		268666: 'Homelife Realty Services',
		268667: 'Coldwell Banker Affiliates of Canada',
		268668: 'Re/Max of Western Canada',
		268669: 'Re/Max Québec Inc.',
		268670: 'Prudential Real Estate Affiliates of Canada Ltd.',
		268672: 'Realty World - Canada',
		268673: 'Elliot Better Homes and Gardens',
		268674: 'Exit Realty Lake Superior',
		268675: 'Realty World By The Sea',
		268676: 'The Beach & Beyond Realty/Better Homes and Gardens',
		268677: 'M. Biggins Real Estate Better Homes and Gardens',
		268678: 'Peak Realty Ltd',
		268679: 'Trans Canada Realty',
		268680: 'CB Richard Ellis Limited',
		268681: 'Reseau Immobilier La Capitale',
		268682: 'Groupe Trans Action Service De Courtage Inc.',
		268683: 'Colliers Macaulay Nicolls Inc.',
		268684: 'CIR',
		268685: 'Exit Realty',
		268686: 'GMAC',
		268687: 'Keller Williams',
		268705: 'Macdonald',
		268706: 'Maxwell',
		268707: 'Sotheby\'s',
		268708: 'Sutton Quebec',
		268709: 'Independent',
		268710: 'Seller\'s Choice',
		268711: 'Assist 2 Sell',
		268712: 'Realty Executive',
		268713: 'La Capitale',
		270618: 'Better Homes and Gardens Real Estate Canada',
		270637: '',
		271687: '',
		271690: '',
		280546: 'Better Homes and Gardens Real Estate LLC',
		290178: 'Realty Executives',
		86516: 'Royal LePage'
    };

	map.OrganizationType = {
		1: 'Affiliate',
		2: 'Firm',
		3: 'Territorial Association',
		4: 'Franchisor',
		5: 'Provincial Association',
		6: 'National Association',
		7: 'Sponsor',
		8: 'Unknown',
		9: 'Technology Provider'
    };

	map.OrganizationDesignations = {
		1: 'Affiliated real estate broker',
		110: 'Brokerage',
		111: 'Brokerage, Independently Owned and Operated',
		112: 'Real Estate Agency',
		113: 'Real Estate Mortgage Agency',
		114: 'Residential Real Estate Agency',
		115: 'Commercial Real Estate Agency',
		116: 'Certified Real Estate Broker',
		117: 'Residential and Commercial Real Estate Agency',
		118: 'Residential and Mortgage Real Estate Agency',
		119: 'Commercial and Mortgage Real Estate Agency',
		120: 'Real Estate Broker',
		121: 'Commercial Real Estate Broker',
		122: 'Commercial and Mortgage Real Estate Broker',
		123: 'Real Estate Mortgage Broker',
		124: 'Residential Real Estate Broker',
		125: 'Residential and Commercial Real Estate Broker',
		126: 'Residential and Mortgage Real Estate Broker',
		2: 'Chartered real estate broker'
    };

}
